# -*- coding: utf-8 -*-
"""sprint_mlam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17f1Pb_i62U8A1pQYpvafXqZa7Qab1Uvs
"""

from numpy import random
import pandas as pd
database = pd.read_csv("/content/Electric_Vehicle_Population_Data.csv")
amostra = database.sample(n=100, random_state=100)
amostra.head()

# Questão número 1
# Variáveis qualitativas
# nominais
amostra[["Make"]]

# nominais
amostra[["Electric Vehicle Type"]]

# ordinais
amostra[["Clean Alternative Fuel Vehicle (CAFV) Eligibility"]]

# ordinais
amostra[["Electric Vehicle Type"]]

# Variáveis quantitativas
# discretas
amostra[["Model Year"]]

# discretas
amostra[["Postal Code"]]

# contínuas
amostra[["Electric Range"]]

# contínuas
amostra[["Base MSRP"]]

# Questão número 2
# a) quantitativa discreta
tabela_freq = amostra["Model Year"].value_counts().sort_index()
print(tabela_freq)
# Insight 1: os anos de fabricação mais recentes apresentam maiores frequências, indicando crescimento da adoção de veículos elétricos nos últimos anos.
# Insight 2: a frequência acumulada mostra que grande parte dos veículos da base foi fabricada após 2020, evidenciando uma frota relativamente nova.

# b) quantitativa contínua
tabela_freq = amostra["Electric Range"].value_counts().sort_index()
print(tabela_freq)
# Insight 1: há uma grande concentração de veículos com autonomia elétrica igual a zero, indicando que muitos registros correspondem a veículos híbridos ou com autonomia elétrica não informada.
# Insight 2: entre os veículos com autonomia diferente de zero, observa-se uma variação ampla de alcance, sugerindo diferentes níveis de tecnologia e capacidade de bateria na frota.